# Generated by Django 2.1.7 on 2019-02-17 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
