# Generated by Django 2.1.7 on 2019-02-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_store_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='date_posted',
        ),
    ]
